export const CAR = {
     GET_CAR_REQUEST : 'GET_CAR_REQUEST',
     GET_CAR_SUCCESS : 'GET_CAR_SUCCESS',
     GET_CAR_FAILED : 'GET_CAR_FAILED',
}

export const CARS = {
    GET_CARS_REQUEST: 'GET_CARS_REQUEST',
    GET_CARS_SUCCESS: 'GET_CARS_SUCCESS',
    GET_CARS_FAILED: 'GET_CARS_FAILED',
}

export const CartActionTypes = {
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CAR'
}


