
const cars = [
      
        {
            id: 1,
            PurchasePrice: 1200000,
            CarType: "Toyota Fielder",
            Year: 2019,
            image: "https://topcar.co.ke/wp-content/uploads/2020/01/2013-Toyota-Fielder-10.jpg",
            carID: 202046,
            BodyType: "Station Wagons",
            FuelType: "Petrol",
            condition: "Foreign Used",
            Transmission: "Automatic",
            Drive: "2WD",
            Milleage: "50,000km",
            EngineSize: "1500cc",
            ExteriorColor: "White",
            InteriorColor: "Jet Black"
        },
        {
            id: 2,
            PurchasePrice: 900000,
            Year: 2018,
            CarType: "Mazde Demio",
            image: "https://topcar.co.ke/wp-content/uploads/2019/07/2013-Mazda-Demio-2.jpg",
            carID: 201198,
            BodyType: "Station Wagons",
            FuelType: "Petrol",
            condition: "Foreign Used",
            Transmission: "Automatic",
            Drive: "2WD - 4DW ",
            Milleage: "50,000km",
            EngineSize: "1300cc",
            ExteriorColor: "Black",
            InteriorColor: "Jet Black"
        },
        {
            id: 3,
            PurchasePrice: 850000,
            Year: 2019,
            CarType: "Toyota Axio",
            image: "https://topcar.co.ke/wp-content/uploads/2018/10/2012-Toyota-Axio-.jpg",
            carID: 202298,
            BodyType: "Station Wagons",
            FuelType: "Petrol",
            condition: "Foreign Used",
            Transmission: "Automatic",
            Drive: "2WD - 4DW ",
            Size: "5 seater",
            Milleage: "50,000km",
            EngineSize: "1500cc",
            ExteriorColor: "Grey",
            InteriorColor: "Grey"
        },
        {
            id: 4,
            PurchasePrice: 5500000,
            Year: 2019,
            CarType: "Toyota Prado",
            image: "https://cdn.pixabay.com/photo/2018/03/21/02/39/toyota-3245397_960_720.jpg",
            carID: 202668,
            FuelType: "Petrol",
            condition: "Foreign Used",
            Transmission: "Automatic",
            Drive: "2WD - 4DW ",
            Size: "5 seater",
            Milleage: "50,000km",
            EngineSize: "2200cc",
            ExteriorColor: "Black",
            InteriorColor: "Jet Black"
        },
        
        // {
        //     "id": 5,
        //     "PurchasePrice": 1800000,
        //     "Year": 2019,
        //     "CarType": "Subaru Forest",
        //     "image": "https://topcar.co.ke/wp-content/uploads/2019/09/2013-Subaru-Forester-Nairobi.jpg",
        //     "carID": 202668,
        //     "FuelType": "Petrol",
        //     "condition": "Foreign Used",
        //     "Transmission": "Automatic",
        //     "Drive": "2WD - 4DW ",
        //     "Size": "5 seater",
        //     "Mileage": "50,000km",
        //     "EngineSize": "2000cc",
        //     "ExteriorColor": "White",
        //     "InteriorColor": "White"
        // },
        // {
        //     "id": 6,
        //     "PurchasePrice": 500000,
        //     "Year": 2019,
        //     "CarType": "Honda Fit",
        //     "image": "https://topcar.co.ke/wp-content/uploads/2020/03/2013-Honda-Fit-3.jpg",
        //     "carID": 202668,
        //     "FuelType": "Petrol",
        //     "condition": "Foreign Used",
        //     "Transmission": "Automatic",
        //     "Drive": "2WD - 4DW ",
        //     "Size": "5 seater",
        //     "Mileage": "50,000km",
        //     "EngineSize": "2000cc",
        //     "ExteriorColor": "Grey",
        //     "InteriorColor": "White"
        // },
        // {
        //     "id": 7,
        //     "PurchasePrice": 1900000,
        //     "Year": 2019,
        //     "CarType": "Nissan X-Trail",
        //     "image": "https://topcar.co.ke/wp-content/uploads/2020/03/2013-Nissan-X-Trail1.jpg",
        //     "carID": 202668,
        //     "FuelType": "Petrol",
        //     "condition": "Foreign Used",
        //     "Transmission": "Automatic",
        //     "Drive": "2WD - 4DW ",
        //     "Size": "5 seater",
        //     "Mileage": "50,000km",
        //     "EngineSize": "2000cc",
        //     "ExteriorColor": "White and Black ",
        //     "InteriorColor": "White"
        // },
        // {
        //     "id": 8,
        //     "PurchasePrice": 1900000,
        //     "Year": 2019,
        //     "CarType": "Subaru Exiga",
        //     "image": "https://topcar.co.ke/wp-content/uploads/2018/10/Subaru-Exiga-for-sale-in-Kenya-1.jpg",
        //     "carID": 202168,
        //     "FuelType": "Petrol",
        //     "condition": "Foreign Used",
        //     "Transmission": "Automatic",
        //     "Drive": "2WD - 4DW ",
        //     "Size": "5 seater",
        //     "Mileage": "50,000km",
        //     "EngineSize": "2500cc",
        //     "ExteriorColor": "Black ",
        //     "InteriorColor": "White"
        // },
        // {
        //     "id": 9,
        //     "PurchasePrice": 1400000,
        //     "Year": 2019,
        //     "CarType": "Toyota Wish",
        //     "image": "https://topcar.co.ke/wp-content/uploads/2020/04/2013-Toyota-Wish-9.jpg",
        //     "carID": 202168,
        //     "FuelType": "Petrol",
        //     "condition": "Foreign Used",
        //     "Transmission": "Automatic",
        //     "Drive": "2WD-4DW ",
        //     "Size": "7 seater",
        //     "Mileage": "50,000km",
        //     "EngineSize": "1800cc",
        //     "ExteriorColor": "Brown ",
        //     "InteriorColor": "Black"
        // },
        // {
        //     "id": 10,
        //     "PurchasePrice": 3000000,
        //     "Year": 2019,
        //     "CarType": "Mercedes E-Class",
        //     "image": "https://cdn.pixabay.com/photo/2016/05/03/23/46/mercedes-benz-1370536__340.jpg",
        //     "carID": 202168,
        //     "FuelType": "Petrol & Diesel",
        //     "condition": "Foreign Used",
        //     "Transmission": "Automatic",
        //     "Drive": "2WD-4DW ",
        //     "Size": "7 seater",
        //     "Mileage": "50,000km",
        //     "EngineSize": "3000cc",
        //     "ExteriorColor": "Red ",
        //     "InteriorColor": "White"
        // },
        // {
        //     "id": 11,
        //     "PurchasePrice": 3300000,
        //     "Year": 2019,
        //     "CarType": "Lexus RX",
        //     "image": "https://topcar.co.ke/wp-content/uploads/2019/12/2013-Lexus-RX270-13.jpg",
        //     "carID": 202168,
        //     "FuelType": "Petrol & Diesel",
        //     "condition": "Foreign Used",
        //     "Transmission": "Automatic",
        //     "Drive": "2WD-4DW ",
        //     "Size": "7 seater",
        //     "Mileage": "50,000km",
        //     "EngineSize": "3000cc",
        //     "ExteriorColor": "White ",
        //     "InteriorColor": "Grey"
        // },
        // {
        //     "id": 12,
        //     "PurchasePrice": 5000000,
        //     "Year": 2019,
        //     "CarType": "GMC - Yuko",
        //     "image": " https: //cdn.motor1.com/images/mgl/Z3w9o/s3/2021-ford-bronco.webp",
        //     "carID": 202168,
        //     "FuelType": "Petrol & Diesel",
        //     "condition": "Foreign Used",
        //     "Transmission": "Automatic",
        //     "Drive": "2WD-4DW ",
        //     "Size": "7 seater",
        //     "Mileage": "50,000km",
        //     "EngineSize": "3000cc",
        //     "ExteriorColor": "Red ",
        //     "InteriorColor": "White"
        // },
        // {
        //     "id": 13,
        //     "PurchasePrice": 4400000,
        //     "Year": 2019,
        //     "CarType": "Yukon",
        //     "image": " https://www.chicagoautoshow.com/assets/1/23/VehicleRegularDimensionId/2021-GMC-Yukon-1.jpg",
        //     "carID": 202168,
        //     "FuelType": "Petrol & Diesel",
        //     "condition": "Foreign Used",
        //     "Transmission": "Automatic",
        //     "Drive": "2WD-4DW ",
        //     "Size": "7 seater",
        //     "Mileage": "50,000km",
        //     "EngineSize": "3500cc",
        //     "ExteriorColor": "Grey",
        //     "InteriorColor": "White"
        // }
    
    ]
    
export default cars;
